name: '💡 Feature request'
description: Suggest an idea for this project
labels:
  - enhancement
  - triage
body:
  - type: textarea
    attributes:
      label: Problem Description
      description: Please describe what kind of problem are you trying to solve
      placeholder: I'm not able to ... because ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Solution
      description: Please describe what would you like to happen
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered and why they didn't work
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: Any other context or screenshots about the feature request
